### ISSUE TITLE
This installation is not working on TK1

### ISSUE THREAD

**Issue by visineo** [dat-ai/tensorflow-on-nvidia-jetson#3]
ubuntu@tegra-ubuntu:~/tensorfow-nvidia-jetson$ sudo pip install tensorflow-0.8.0-py2-none-any.whl
The directory '/home/ubuntu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ubuntu/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: tensorflow==0.8.0 from file:///home/ubuntu/tensorfow-nvidia-jetson/tensorflow-0.8.0-py2-none-any.whl in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: numpy>=1.8.2 in /usr/local/lib/python2.7/dist-packages (from tensorflow==0.8.0)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python2.7/dist-packages (from tensorflow==0.8.0)
Requirement already satisfied: protobuf==3.0.0b2 in /usr/local/lib/python2.7/dist-packages (from tensorflow==0.8.0)
Requirement already satisfied: wheel in /usr/lib/python2.7/dist-packages (from tensorflow==0.8.0)
Requirement already satisfied: setuptools in /usr/lib/python2.7/dist-packages (from protobuf==3.0.0b2->tensorflow==0.8.0)
ubuntu@tegra-ubuntu:~/tensorfow-nvidia-jetson$ python
Python 2.7.6 (default, Jun 22 2015, 18:31:26) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:99] Couldn't open CUDA library libcudnn.so. LD_LIBRARY_PATH: /usr/local/cuda/lib:/usr/local/cuda-6.5/lib:
I tensorflow/stream_executor/cuda/cuda_dnn.cc:1562] Unable to load cuDNN DSO
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 55, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named protobuf

Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.

**Comment by MyAusweis** [comment]
where did you find this file ?  patch -p1 < ../tensorflow_0.12.1_jetsontk1.patch

**Comment by MyAusweis** [comment]
where did you find this file ? patch -p1 < ../tensorflow_0.12.1_jetsontk1.patch

**Comment by SudhirBhadauria** [comment]
how to get the patch as mentioned? patch -p1 < ../tensorflow_0.12.1_jetsontk1.patch.
Any luck in building latest one?
